<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>SERVICE</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <link rel="stylesheet" type="text/css" href="s11.css">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
<style>

            body 
                    {
                        font-family: Arial, Helvetica, sans-serif;
                        
background-color:#F3D2B2;
                        margin:50px;
                        min-height: 300px; 
                        background-position: center;
                        background-repeat: no-repeat;
                        background-size: cover;
                        position:relative;
                    }
                   
                 
			

	.bs-example{
    	margin: 20px;
    }
</style>
</head>
<body>
<div class="bs-example">
    <nav class="navbar navbar-expand-md navbar-light bg-light">
        <a href="#" class="navbar-brand">HOME</a>
        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div id="navbarCollapse" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
               <li class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">BRANCH</a>
                    <div class="dropdown-menu">
                        <a href="BRANCH.PHP" class="dropdown-item">ADD BRANCH</a>
                        <a href="rbranch.php" class="dropdown-item">REPORT OF THE BRANCH</a>
                        <a href="editbranch.php" class="dropdown-item">UPDATE BRANCH</a>
                       
                </li>
		<li class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">EMPLOYEE</a>
                    <div class="dropdown-menu">
                        <a href="EMPLOYEE.PHP" class="dropdown-item">ADD EMPLOYEE</a>
                        <a href="REMPLOYEE.php" class="dropdown-item">REPORT OF THE EMPLOYESS</a>
                        <a href="uemployee.PHP" class="dropdown-item">UPDATE EMPLOYEE</a>
                        
                </li>
             
                <li class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">SUPPLIER</a>
                    <div class="dropdown-menu">
                        <a href="SUPPLIER.PHP" class="dropdown-item">ADD SUPPLIER</a>
                        <a href="rsupplier.php" class="dropdown-item">REPORT OF THE SUPPLIER</a>
                        <a href="usupplier.php" class="dropdown-item">UPDATE SUPPLIER</a>
                        
                </li>
            

                <li class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">MACHINE</a>
                    <div class="dropdown-menu dropdown-menu-right">
                        <a href="MACHINE.PHP" class="dropdown-item">ADD MACHINES</a>
                        <a href="rmachine.php" class="dropdown-item">REPORT OF THE MACHINES</a>
			<a href="umachine.php" class="dropdown-item">UPDATE MACHINES</a>
                        
                </li>
		<li class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">TANKER</a>
                    <div class="dropdown-menu">
                        <a href="TANKER.PHP" class="dropdown-item">ADD TANKER</a>
                        <a href="rtanker.php" class="dropdown-item">REPORT OF TANKERS</a>
                        <a href="utanker.php" class="dropdown-item">UPDATE TANKER</a>
                       
                </li>
<li class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">SALES</a>
                    <div class="dropdown-menu">
                        <a href="SALES.PHP" class="dropdown-item">ADD SALES</a>
                        <a href="rsales.php" class="dropdown-item">REPORT OF THE SALES</a>
                        <a href="usales.php" class="dropdown-item">UPDATE SALES</a>
                        
                </li>
            </ul>
        </div>
<a href="LOGIN.PHP" class="navbar-brand">LOGOUT</a>
        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>
    </nav>
</div>
</body>
</html>                                                        